---
kind: pipeline
type: ssh
name: Tutorial

server:
  host: 192.168.5.10
  user:
    from_secret: SSH_USER
  password:
    from_secret: SSH_PASSWORD

clone:
  disable: true

steps:
  - name: test_CMD
    commands:
      - cd supportdecours
      - git pull

