---
kind: pipeline
type: ssh
name: Tutorial


clone:
  disable: true

server:
  host: 192.168.5.10
  user:
    from_secret: SSH_USER
  password:
    from_secret: SSH_PASSWORD

steps:
  - name: Stop and remove old version
    commands:
      - [[ -d /root/supportformation ]] && cd /root/supportformation ; docker compose down ; cd /tmp ; rm -rf /root/supportformation

  - name: Clone new version
    commands:
      - git clone https://github.com/kumalabsconsulting/supportformation.git /root/

  - name: Launch site
      - cd /root/supportformation
      - docker compose up -d


trigger:
  ref:
    - refs/heads/main
    - refs/heads/**