---
kind: pipeline
type: ssh
name: Tutorial

trigger:
  branch:
    - main

clone:
  disable: true

server:
  host: 192.168.5.10
  user:
    from_secret: SSH_USER
  password:
    from_secret: SSH_PASSWORD

steps:
  - name: test_CMD
    commands:
      - cd supportdecours
      - git pull

