---
kind: pipeline
type: ssh
name: Tutorial


clone:
  disable: true

server:
  host: 192.168.5.10
  user:
    from_secret: SSH_USER
  password:
    from_secret: SSH_PASSWORD

steps:
  - name: Stop and remove old version
    commands: |
      if [[ -d /root/supportformation ]]
      then 
        cd /root/supportformation
        docker compose down
        cd /tmp
        rm -rf /root/supportformation
      fi

  - name: Clone new version
    commands:
      - git clone https://github.com/kumalabsconsulting/supportformation.git /root/supportformation

  - name: Launch site
    commands:
      - cd /root/supportformation
      - docker compose up -d


trigger:
  ref:
    - refs/heads/main
    - refs/heads/**